---
swagger: "2.0"
info:
  description: "Other functions needed by anyone using the platform"
  version: "1.0"
  title: "Platform Utility function "
host: "virtserver.swaggerhub.com"
basePath: "/ndid/utility/0.1"
schemes:
- "https"
paths:
  /utility/idp:
    get:
      summary: "Retrieve all idp id"
      description: "asdf"
      operationId: "get_idp_list"
      consumes:
      - "application/json"
      parameters:
      - name: "min_ial"
        in: "query"
        description: "minimum ial suppored by IDP looking for"
        required: false
        type: "integer"
      - name: "min_aal"
        in: "query"
        description: "minimum aal suppored by IDP looking for"
        required: false
        type: "integer"
      responses:
        200:
          description: "IDP found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/IDP"
        400:
          description: "Error: MIN IAL, AAL value"
        404:
          description: "Error: No IDP found"
      x-swagger-router-controller: "Default"
  /utility/idp/{namespace}/{identifier}:
    get:
      summary: "Retrieve all idp node_id relevant to/authorized by this {namespace}/{identifier}"
      description: "asdf"
      operationId: "get_idp_list_for_identifier"
      consumes:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      - name: "min_ial"
        in: "query"
        description: "minimum ial suppored by IDP looking for"
        required: false
        type: "integer"
      - name: "min_aal"
        in: "query"
        description: "minimum aal suppored by IDP looking for"
        required: false
        type: "integer"
      responses:
        200:
          description: "IDP found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/IDP"
        400:
          description: "Error: Invalid Identity or MIN IAL, AAL value"
        404:
          description: "Error: No IDP found"
      x-swagger-router-controller: "Default"
  /utility/as/{service_id}:
    get:
      summary: "Retrieve list of id of all available as given a service id"
      description: "asdf"
      operationId: "get_as_id_list"
      parameters:
      - name: "service_id"
        in: "path"
        description: "Service ID"
        required: true
        type: "string"
      responses:
        200:
          description: "AS ID found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AS"
      x-swagger-router-controller: "Default"
definitions:
  IDP:
    type: "object"
    required:
    - "idp_id"
    - "idp_name"
    - "min_aal"
    - "min_ial"
    properties:
      idp_name:
        type: "string"
      idp_id:
        type: "string"
      min_ial:
        type: "integer"
      min_aal:
        type: "integer"
    example:
      min_aal: 6
      idp_name: "idp_name"
      idp_id: "idp_id"
      min_ial: 0
  AS:
    type: "object"
    required:
    - "as_id"
    - "as_name"
    - "min_aal"
    - "min_ial"
    properties:
      as_name:
        type: "string"
      as_id:
        type: "string"
      min_ial:
        type: "integer"
      min_aal:
        type: "integer"
    example:
      min_aal: 6
      as_id: "as_id"
      min_ial: 0
      as_name: "as_name"
