---
swagger: "2.0"
info:
  description: "Identity Management API Spec"
  version: "1.0"
  title: "Identity API"
host: "virtserver.swaggerhub.com"
basePath: "/ndid/Identity/0.1"
schemes:
- "https"
paths:
  /identity:
    post:
      summary: "Create Identity Record"
      description: "IDP calls this method to create a new identity"
      operationId: "create_identity"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "identity"
        description: "Identity data needed to create identity.  Please note that 'namespace',\
          \ 'identifier', and 'secret' are not stored directly.  Rather, Hash(namespace,\
          \ identifier, secret) are created and stored.  Secret is not shared with\
          \ any other IDP, rather is used by each IDP to prove it knows this person\
          \ after having been granted permission to access this Identity.  In addition,\
          \ this method provide privacy across IDP, as each IDP does not know what\
          \ other IDP knows about this same person if IDP does not know the secret."
        required: true
        schema:
          $ref: "#/definitions/Identity"
      responses:
        201:
          description: "Identity Created"
        400:
          description: "Error: Invalid accessor method or accessor value"
        403:
          description: "Error: Identity already exist"
      x-swagger-router-controller: "Default"
  /identity/{namespace}/{identifier}:
    get:
      summary: "Fetch namespace/identifier"
      description: "asdf"
      operationId: "check_identity"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      responses:
        200:
          description: "ID exist"
        404:
          description: "ID not found"
      x-swagger-router-controller: "Default"
    post:
      summary: "Submit new identifiers for {namespace}/{identifier}"
      description: "asdf"
      operationId: "add_identifier"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      - in: "body"
        name: "new_identifiers"
        description: "Additional identifiers for this ID to add"
        required: true
        schema:
          $ref: "#/definitions/Identifiers"
      responses:
        200:
          description: "Endorsement Successful"
        400:
          description: "Error: Invalid endorsement type"
        404:
          description: "Error: Identity does not exist"
      x-swagger-router-controller: "Default"
  /identity/{namespace}/{identifier}/endorsement:
    get:
      summary: "Fetch Endorsement list for {namespace}/{identifier}"
      description: "TBD"
      operationId: "get_endorsement"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      responses:
        200:
          description: "Endorsement Exist"
          schema:
            $ref: "#/definitions/Endorsements"
        404:
          description: "No endorsement Exist"
      x-swagger-router-controller: "Default"
    post:
      summary: "Submit endorsement for {namespace}/{identifier}"
      description: "asdf"
      operationId: "endorse_identity"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      - in: "body"
        name: "endorsements"
        description: "endorsement"
        required: true
        schema:
          $ref: "#/definitions/Identity"
      responses:
        200:
          description: "Endorsement Successful"
        400:
          description: "Error: Invalid endorsement type"
        404:
          description: "Error: Identity does not exist"
      x-swagger-router-controller: "Default"
  /identity/{namespace}/{identifier}/accessors:
    post:
      summary: "Add accessor method"
      description: "asdf"
      operationId: "add_accessor_method"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      - in: "body"
        name: "accessors"
        description: "endorsement"
        required: true
        schema:
          $ref: "#/definitions/Accessors"
      responses:
        200:
          description: "Endorsement Successful"
        400:
          description: "Error: Invalid accessor type"
        404:
          description: "Error: Identity does not exist"
      x-swagger-router-controller: "Default"
  /identity/{namespace}/{identifier}/requests/history:
    get:
      summary: "Fetch Request History list for {namespace}/{identifier}"
      description: "TBD"
      operationId: "get_request_history"
      parameters:
      - name: "namespace"
        in: "path"
        description: "ID Namespace"
        required: true
        type: "string"
      - name: "identifier"
        in: "path"
        description: "Identifier for the ID"
        required: true
        type: "string"
      - name: "count"
        in: "query"
        description: "Number of request to get"
        required: false
        type: "string"
      responses:
        200:
          description: "Requests Exist"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Requests"
        404:
          description: "No request Exist"
      x-swagger-router-controller: "Default"
definitions:
  Identity:
    type: "object"
    required:
    - "accessor_id"
    - "accessor_key"
    - "accessor_type"
    - "identifier"
    - "namespace"
    - "secret"
    properties:
      namespace:
        type: "string"
      identifier:
        type: "string"
      secret:
        type: "string"
      accessor_type:
        type: "string"
      accessor_key:
        type: "string"
      accessor_id:
        type: "string"
    example:
      identifier: "identifier"
      accessor_id: "accessor_id"
      accessor_type: "accessor_type"
      namespace: "namespace"
      secret: "secret"
      accessor_key: "accessor_key"
  Endorsements:
    type: "object"
    required:
    - "endorsement_type"
    properties:
      endorsement_type:
        type: "string"
      endrosement_value:
        type: "string"
    example:
      endorsement_type: "endorsement_type"
      endrosement_value: "endrosement_value"
  Identifiers:
    type: "object"
    required:
    - "identifiers"
    properties:
      identifiers:
        type: "array"
        items:
          type: "string"
    example:
      identifiers:
      - "identifiers"
      - "identifiers"
  Accessors:
    type: "object"
    required:
    - "accessor_id"
    - "accessor_key"
    - "accessor_type"
    properties:
      accessor_type:
        type: "string"
      accessor_key:
        type: "string"
      accessor_id:
        type: "string"
        description: "ID of the accessor method.  Used to indicate which accessor\
          \ method is used to sign consent/permission on behalf of this Identity"
    example:
      accessor_id: "accessor_id"
      accessor_type: "accessor_type"
      accessor_key: "accessor_key"
  Requests:
    type: "object"
    required:
    - "request_id"
    properties:
      request_id:
        type: "string"
      request_body:
        type: "string"
    example:
      request_body: "request_body"
      request_id: "request_id"
